apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearchlb
  namespace: kube-system
  labels:
    component: elasticsearch
    role: load-balancer
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: load-balancer
  template:
    metadata:
      labels:
        component: elasticsearch
        role: load-balancer
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearchlb
        image: tacodata/elasticsearch:lb
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
