apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearchdata
  namespace: kube-system
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearchdata
        image: tacodata/elasticsearch:data
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
